use_frameworks!

platform :ios, '8.0'

target 'TNews_Example' do
  pod 'TNews', :path => '../'

  target 'TNews_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
